[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"
 [[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

